### ISSUE TITLE
xml results are insta-deleted when used with Codeception 2.2.9

### ISSUE THREAD

**Issue by etki** [allure-framework/allure-codeception#25]
Currently following config
```
  config:
    Yandex\Allure\Adapter\AllureAdapter:
      deletePreviousResults: true
      outputDirectory: ../Metadata/Allure
```
simply deletes all results right after tests are run (or prevent them from spawning in the first place).

There is possibility i'll fix it myself and send a PR, but not sure if i'll have spare time as well
