### ISSUE TITLE
The allure report doesn't take into account Gherkin feature files

### ISSUE THREAD

**Issue by alexrotaru** [allure-framework/allure-codeception#28]
Hi all,

We've configured the latest dev version with codeception 2.2.10
```
extensions:
    enabled: 
        - Codeception\Extension\RunFailed
        - Yandex\Allure\Adapter\AllureAdapter
    config:
        Yandex\Allure\Adapter\AllureAdapter:
            deletePreviousResults: false
            outputDirectory: allure-results
```

We have the following feature file in tests/acceptance:

```
@login
Feature: login
  As a registered user
  I want the ability to login
  Using email and password

  Scenario Outline: Login
    Given that I am on "Home Page"
    When I go to "Login Page"
      And I enter <email> as the email address
      And I enter <password> as the password
      And I login
    Then I should be on <page>

    Examples:
      | email                                  | password            | page                     |
      | "email@email.com"          | "pass1!"     | "Account Dashboard Page" |
      | "incorect@email.com"     | "pass1!"     | "Login Page"             |
      | "email@email.com"          | "incorrectPassword" | "Login Page"             |
```

We can run the tests and they behave as expected.
When I run  `allure generate tests/_output/allure-results ` (I have on my mac allure command line tools 1.4.23 installed with brew) I get a report with the following issues:
- there's no feature name
- there's no story name
- the Feature description from my feature file appear as steps in the report
- none of the steps defined in the Scenario Outline appear in the report
- only Actor actions appear in the report (for example `$I->click()`).

Please see a screenshot with the obtained report:
![codeception_gherking_allure_report](https://cloud.githubusercontent.com/assets/3822903/25751959/74a74c22-31bf-11e7-9f9b-12b3d37309fa.png)

I also attached the xml file (you need to change the extension from .txt to .xml).
[4f8a921d-2dfe-48c3-a065-008b71f1c234-testsuite.txt](https://github.com/allure-framework/allure-codeception/files/979536/4f8a921d-2dfe-48c3-a065-008b71f1c234-testsuite.txt)
