### ISSUE TITLE
Can't get test body for Allure reports using Codeception adapter (v.1.5.2)

### ISSUE THREAD

**Issue by fifle** [allure-framework/allure-codeception#89]
**Describe the bug**
:wave: 
I’ve got a question related to connecting Allure adapter for Codeception (v 1.5.2). I’ve set it up for the project (followed same settings as it’s shown for [demo project on Github](https://github.com/allure-examples/allure-codeception-example)) ([see screenshot #1](https://imgur.com/X8sXvVI)), but it looks that it doesn’t really fetch test result data from .XML file generated under allure-results folder [(see screenshot #2)](https://imgur.com/JaszDWR). The .xml itself has all the steps and failure details, while the report misses all this data, except the one indicated within Codeception’s report.xml - Cest name and status. ([see screenshot #3](https://imgur.com/MBqCWzw))

What could be wrong here? Should I somehow manipulate with outputDirectory for that?

Configs for Allure are stored in acceptance.suite.yml :
```
actor: AcceptanceTester
step_decorators:
  - \Codeception\Step\Retry
  - \Codeception\Step\TryTo

extensions:
  enabled:
    - Yandex\Allure\Codeception\AllureCodeception
    - Codeception\Extension\Recorder
    - Codeception\Extension\Logger
  config:
    Yandex\Allure\Codeception\AllureCodeception:
      deletePreviousResults: true
      outputDirectory: allure-results
      ignoredAnnotations:
        - env
        - dataprovider
        - skip
```
The command for running tests:
`docker-compose exec tests codecept run acceptance BrandAmbassadorCest --env chrome --steps --xml --html
`The command for running Allure server locally:
`allure serve tests/_output`

**To Reproduce**
1. Get a new/existing PHP project with latest Codeception on board
2. Setup Allure CLI
3. Setup composer.json with Codeception and allure-codeception adapter dependencies
4. Add custom configurations into acceptance.suite.yml
5. Have at least one failing Cest that produce screenshots and other artifacts
6. Execute tests, check if allure-reports folder has appeared under _tests folder in Codeception project
7. Run Allure serve command and check if you're able to see Test body under Suites section.

**Expected behavior**
Test body should include all test execution steps and screenshots generated by Codeception.

**Screenshots**
Screenshots [available here on Imgur](https://imgur.com/a/eS7vHio)

**Additional context**
[I've contacted Codeception community on their Slack channel](https://codeception.slack.com/archives/C93HPU7NZ/p1645433145482329) regarding that issue and they have referred me to your repo.
